#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# brett documentation build configuration file, created by
# sphinx-quickstart on Wed Jun  6 11:48:29 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.




import os
import sys
from recommonmark.parser import CommonMarkParser
sys.path.insert(0, os.path.abspath('..'))
import sphinx_bootstrap_theme

# ...

# Activate the theme.


def setup(app):
    app.add_stylesheet("my-styles.css") # also can be a full URL
# app.add_stylesheet("ANOTHER.css")
# app.add_stylesheet("AND_ANOTHER.css")


extensions = ['sphinx.ext.doctest',
              'sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.mathjax',
              'sphinx.ext.ifconfig',
              'sphinx.ext.viewcode',
              'sphinx.ext.githubpages']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_parsers = {
    '.md': CommonMarkParser,
}
source_suffix = ['.txt','.rst','.md','.MD']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Brettlv\'s Website'
copyright = '2018, Brettlv'
author = 'Brettlv'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '3'
# The full version, including alpha/beta/rc tags.
release = '3'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#

html_theme_options = {
    'navbar_title': "Brettlv's Blog",
    'navbar_site_name': "https://brettlv.github.io/",
    'navbar_links': [
                     ("Home", "Page"),
                     ],
        
                     # Render the next and previous page links in navbar. (Default: true)
                     'navbar_sidebarrel': True,
                     
                     # Render the current pages TOC in the navbar. (Default: true)
                     'navbar_pagenav': True,
                     
                     # Tab name for the current pages TOC. (Default: "Page")
                     'navbar_pagenav_name': "Page",
                     
                     # Global TOC depth for "site" navbar tab. (Default: 1)
                     # Switching to -1 shows all levels.
                     'globaltoc_depth': 2,
                     
                     # Include hidden TOCs in Site navbar?
                     #
                     # Note: If this is "false", you cannot have mixed ``:hidden:`` and
                     # non-hidden ``toctree`` directives in the same page, or else the build
                     # will break.
                     #
                     # Values: "true" (default) or "false"
                     'globaltoc_includehidden': "true",
                     
                     # HTML navbar class (Default: "navbar") to attach to <div> element.
                     # For black navbar, do "navbar navbar-inverse"
                     'navbar_class': "navbar navbar-inverse",
                     
                     # Fix navigation bar to top of page?
                     # Values: "true" (default) or "false"
                     'navbar_fixed_top': "true",
                     
                     # Location of link to source.
                     # Options are "nav" (default), "footer" or anything else to exclude.
                     'source_link_position': "nav",
                     
                     # Bootswatch (http://bootswatch.com/) theme.
                     #
                     # Options are nothing (default) or the name of a valid theme
                     # such as "cosmo" or "sandstone".
                     'bootswatch_theme': "united",
                     
                     # Choose Bootstrap version.
                     # Values: "3" (default) or "2" (in quotes)
    'bootstrap_version': "3",

}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'BrettlvsWebsitedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#
# 'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#
# 'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#
# 'preamble': '',

# Latex figure (float) alignment
#
# 'figure_align': 'htbp',
}


latex_engine = 'pdflatex'
latex_elements = {
    'fontpkg': r'''
        \setmainfont{DejaVu Serif}
        \setsansfont{DejaVu Sans}
        \setmonofont{DejaVu Sans Mono}
        ''',
    'preamble': r'''
        \usepackage[titles]{tocloft}
        \cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
        \setlength{\cftchapnumwidth}{0.75cm}
        \setlength{\cftsecindent}{\cftchapnumwidth}
        \setlength{\cftsecnumwidth}{1.25cm}
        ''',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'printindex': r'\footnotesize\raggedright\printindex',
    'papersize': 'letterpaper',

}
latex_show_urls = 'footnote'
latex_additional_files = ["mystyle.sty"]


# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
                   (master_doc, 'BrettlvsWebsite.tex', 'Brettlv\'s Website Documentation',
                    'Brettlv', 'manual'),
                   ]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
             (master_doc, 'brettlvswebsite', 'Brettlv\'s Website Documentation',
              [author], 1)
             ]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
                     (master_doc, 'BrettlvsWebsite', 'Brettlv\'s Website Documentation',
                      author, 'BrettlvsWebsite', 'One line description of project.',
                      'Miscellaneous'),
                     ]




# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

